basePath: /
definitions:
  aggregator.HealthCheck:
    properties:
      component:
        type: string
      stats:
        additionalProperties: true
        type: object
      status:
        type: string
      uptime:
        type: string
    type: object
  internal_api.ConnectionListResponse:
    properties:
      events_by_pid:
        additionalProperties:
          items: {}
          type: array
        description: Events grouped by PID
        type: object
      query_time:
        description: Query timestamp
        example: "2023-01-01T12:00:00Z"
        type: string
      total_events:
        description: Total number of events
        example: 10
        type: integer
      total_pids:
        description: Number of unique PIDs
        example: 3
        type: integer
    type: object
  internal_api.ConnectionSummaryRequest:
    properties:
      command:
        description: Command name
        example: curl
        type: string
      duration_seconds:
        description: Duration in seconds
        example: 60
        type: integer
      pid:
        description: Process ID
        example: 1234
        type: integer
    type: object
  internal_api.ConnectionSummaryResponse:
    properties:
      command:
        description: Command name
        example: curl
        type: string
      count:
        description: Number of connection events
        example: 5
        type: integer
      duration_seconds:
        description: Duration in seconds
        example: 60
        type: integer
      pid:
        description: Process ID
        example: 1234
        type: integer
      query_time:
        description: Query timestamp
        example: "2023-01-01T12:00:00Z"
        type: string
    type: object
  internal_api.EventFilters:
    properties:
      command:
        description: Command filter
        example: curl
        type: string
      limit:
        description: Limit filter
        example: 100
        type: integer
      pid:
        description: Process ID filter
        example: 1234
        type: integer
      since:
        description: Start time filter
        example: "2023-01-01T12:00:00Z"
        type: string
      type:
        description: Event type filter
        example: connection
        type: string
      until:
        description: End time filter
        example: "2023-01-01T13:00:00Z"
        type: string
    type: object
  internal_api.EventsResponse:
    properties:
      count:
        description: Number of events returned
        example: 25
        type: integer
      events:
        description: List of events
        items: {}
        type: array
      filters:
        allOf:
        - $ref: '#/definitions/internal_api.EventFilters'
        description: Applied filters
      query_time:
        description: Query timestamp
        example: "2023-01-01T12:00:00Z"
        type: string
      total_count:
        description: Total number of matching events
        example: 150
        type: integer
    type: object
  internal_api.HealthResponse:
    properties:
      component:
        description: Component name
        example: eBPF Monitor API
        type: string
      status:
        description: Service status
        example: healthy
        type: string
      uptime:
        description: Service uptime
        example: 1h30m
        type: string
      version:
        description: API version
        example: 1.0.0
        type: string
    type: object
  internal_api.PacketDropListResponse:
    properties:
      events_by_pid:
        additionalProperties:
          items: {}
          type: array
        description: Events grouped by PID
        type: object
      query_time:
        description: Query timestamp
        example: "2023-01-01T12:00:00Z"
        type: string
      total_events:
        description: Total number of events
        example: 7
        type: integer
      total_pids:
        description: Number of unique PIDs
        example: 2
        type: integer
    type: object
  internal_api.PacketDropSummaryRequest:
    properties:
      command:
        description: Command name
        example: nginx
        type: string
      duration_seconds:
        description: Duration in seconds
        example: 60
        type: integer
      pid:
        description: Process ID
        example: 1234
        type: integer
    type: object
  internal_api.PacketDropSummaryResponse:
    properties:
      command:
        description: Command name
        example: nginx
        type: string
      count:
        description: Number of packet drop events
        example: 3
        type: integer
      duration_seconds:
        description: Duration in seconds
        example: 60
        type: integer
      pid:
        description: Process ID
        example: 1234
        type: integer
      query_time:
        description: Query timestamp
        example: "2023-01-01T12:00:00Z"
        type: string
    type: object
  internal_api.ProgramInfo:
    properties:
      id:
        description: Program ID
        example: 123
        type: integer
      name:
        description: Program name
        example: connection_tracer
        type: string
      status:
        description: Program status
        example: loaded
        type: string
      type:
        description: Program type
        example: kprobe
        type: string
    type: object
  internal_api.ProgramsResponse:
    properties:
      programs:
        description: List of eBPF programs
        items:
          $ref: '#/definitions/internal_api.ProgramInfo'
        type: array
      query_time:
        description: Query timestamp
        example: "2023-01-01T12:00:00Z"
        type: string
      total_count:
        description: Total number of programs
        example: 2
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: https://github.com/srodi/ebpf-server/issues
  description: HTTP API for eBPF-based network connection and packet drop monitoring
  license:
    name: MIT
    url: https://github.com/srodi/ebpf-server/blob/main/LICENSE
  title: eBPF Network Monitor API
  version: 1.0.0
paths:
  /api/connection-summary:
    get:
      consumes:
      - application/json
      description: Get count of connection events filtered by PID, command, and time
        window
      parameters:
      - description: Process ID (GET only)
        in: query
        name: pid
        type: integer
      - description: Command name (GET only)
        in: query
        name: command
        type: string
      - description: 'Duration in seconds (GET only, default: 60)'
        in: query
        name: duration_seconds
        type: integer
      - description: Connection summary request (POST only)
        in: body
        name: request
        schema:
          $ref: '#/definitions/internal_api.ConnectionSummaryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Connection statistics
          schema:
            $ref: '#/definitions/internal_api.ConnectionSummaryResponse'
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get connection statistics
      tags:
      - connections
    post:
      consumes:
      - application/json
      description: Get count of connection events filtered by PID, command, and time
        window
      parameters:
      - description: Process ID (GET only)
        in: query
        name: pid
        type: integer
      - description: Command name (GET only)
        in: query
        name: command
        type: string
      - description: 'Duration in seconds (GET only, default: 60)'
        in: query
        name: duration_seconds
        type: integer
      - description: Connection summary request (POST only)
        in: body
        name: request
        schema:
          $ref: '#/definitions/internal_api.ConnectionSummaryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Connection statistics
          schema:
            $ref: '#/definitions/internal_api.ConnectionSummaryResponse'
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get connection statistics
      tags:
      - connections
  /api/events:
    get:
      consumes:
      - application/json
      description: Get events filtered by type, PID, command, time range, and limit
      parameters:
      - description: Event type (connection, packet_drop)
        in: query
        name: type
        type: string
      - description: Process ID
        in: query
        name: pid
        type: integer
      - description: Command name
        in: query
        name: command
        type: string
      - description: Start time (RFC3339 format)
        in: query
        name: since
        type: string
      - description: End time (RFC3339 format)
        in: query
        name: until
        type: string
      - description: 'Maximum number of events to return (default: 100)'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Filtered events
          schema:
            $ref: '#/definitions/internal_api.EventsResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Query events
      tags:
      - events
  /api/events/ingest:
    post:
      consumes:
      - application/json
      description: Accept events from eBPF agents for aggregation and storage
      parameters:
      - description: Events to ingest
        in: body
        name: events
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Ingestion result
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            type: string
        "405":
          description: Method not allowed
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Ingest events from agents
      tags:
      - events
  /api/list-connections:
    get:
      consumes:
      - application/json
      description: Get recent connection events grouped by PID
      produces:
      - application/json
      responses:
        "200":
          description: Connection events
          schema:
            $ref: '#/definitions/internal_api.ConnectionListResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List connection events
      tags:
      - connections
  /api/list-packet-drops:
    get:
      consumes:
      - application/json
      description: Get recent packet drop events grouped by PID
      produces:
      - application/json
      responses:
        "200":
          description: Packet drop events
          schema:
            $ref: '#/definitions/internal_api.PacketDropListResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List packet drop events
      tags:
      - packet_drops
  /api/packet-drop-summary:
    get:
      consumes:
      - application/json
      description: Get count of packet drop events filtered by PID, command, and time
        window
      parameters:
      - description: Process ID (GET only)
        in: query
        name: pid
        type: integer
      - description: Command name (GET only)
        in: query
        name: command
        type: string
      - description: 'Duration in seconds (GET only, default: 60)'
        in: query
        name: duration_seconds
        type: integer
      - description: Packet drop summary request (POST only)
        in: body
        name: request
        schema:
          $ref: '#/definitions/internal_api.PacketDropSummaryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Packet drop statistics
          schema:
            $ref: '#/definitions/internal_api.PacketDropSummaryResponse'
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get packet drop statistics
      tags:
      - packet_drops
    post:
      consumes:
      - application/json
      description: Get count of packet drop events filtered by PID, command, and time
        window
      parameters:
      - description: Process ID (GET only)
        in: query
        name: pid
        type: integer
      - description: Command name (GET only)
        in: query
        name: command
        type: string
      - description: 'Duration in seconds (GET only, default: 60)'
        in: query
        name: duration_seconds
        type: integer
      - description: Packet drop summary request (POST only)
        in: body
        name: request
        schema:
          $ref: '#/definitions/internal_api.PacketDropSummaryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Packet drop statistics
          schema:
            $ref: '#/definitions/internal_api.PacketDropSummaryResponse'
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get packet drop statistics
      tags:
      - packet_drops
  /api/programs:
    get:
      consumes:
      - application/json
      description: Get the status and information of all loaded eBPF programs
      produces:
      - application/json
      responses:
        "200":
          description: List of eBPF programs
          schema:
            $ref: '#/definitions/internal_api.ProgramsResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List eBPF programs
      tags:
      - programs
  /api/stats:
    get:
      consumes:
      - application/json
      description: Retrieve statistics about event aggregation including counts by
        type and node
      produces:
      - application/json
      responses:
        "200":
          description: Aggregation statistics
          schema:
            additionalProperties: true
            type: object
        "405":
          description: Method not allowed
          schema:
            type: string
      summary: Get aggregation statistics
      tags:
      - stats
  /health:
    get:
      consumes:
      - application/json
      description: Get the health status of the eBPF monitoring system
      produces:
      - application/json
      responses:
        "200":
          description: Health status
          schema:
            $ref: '#/definitions/internal_api.HealthResponse'
        "503":
          description: Service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
swagger: "2.0"
