apiVersion: v1
kind: Service
metadata:
  name: ebpf-aggregator
  namespace: ebpf-system
  labels:
    app: ebpf-aggregator
    component: aggregator
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: ebpf-aggregator
    component: aggregator
---
apiVersion: v1
kind: Service
metadata:
  name: ebpf-monitor
  namespace: ebpf-system
  labels:
    app: ebpf-monitor
    component: agent
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for DaemonSet
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ebpf-monitor
    component: agent
